### ISSUE TITLE
Maximum function nesting level of '500' reached, aborting! When using $softDelete = true.

### ISSUE THREAD

**Issue by pindamonhangaba** [laravel-ardent/ardent#237]
I get the error if I set $softDelete to true, only when using Ardent.

**Comment by carbontwelve** [comment]
I am surprised this is still open. The reason as chadlockett rightfully said is because soft deletes where moved to a trait in laravel 4.2 meaning that the model will keep hitting its magic call method in an "infinate" loop until hitting the configured nesting level. The fix being to include the trait on all models that have the soft delete property.

**Comment by igorsantos07** [comment]
Thanks for the explanation, @carbontwelve :)
