### ISSUE TITLE
Docs say namespace Laravelbook while should be LaravelArdent

### ISSUE THREAD

**Issue by federico77** [laravel-ardent/ardent#286]
Took me a bit to find out why the library could not be find by my package as I was already having my bit of headache namespacing everything for the Laravel 5.1 migration of my app.

Is there a particular reason why all the docs state that part of the namespace is "LaravelBook" while it is actually "LaravelArdent"? To better explain it. When I reference Ardent I have to do:

`LaravelArdent\Ardent\Ardent` while I was previously using `LaravelBook\Ardent\Ardent`

I might have not got right the whole namespacing thing hence the question... :)

Thanks,
Federico

**Comment by igorsantos07** [comment]
The project was renamed in the new version to comply with the GitHub team -
that was changed so it don't link anymore with the old and unmaintained
website from the original owner, and that don't link to something regarding
"Laravel documentation".

Sorry for the trouble! I'm still trying to figure out a way to migrate the
Composer package name... What was your issue exactly? You had to change the
PHP Namespace only? Could you confirm me the package name in your
composer.json?

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by federico77** [comment]
Hello Igor,

I am referencing to "laravelbook/ardent": "3.*" within composer as per the current docs.
Following the current docs I am asked to use LaravelBook\Ardent\Ardent while it is obviously not a valid namespace anymore.

By the way: thanks a lot for bringing back Ardent to life. I still wonder why something like this wasn't a standard Eloquent feature! :)

**Comment by igorsantos07** [comment]
Here we go:

1. gonna fix the docs on the correct namespace. The vendor changed but I forgot it was mentioned in the docs :)
2. unfortunatelly, [Packagist does not support vendor renaming](https://github.com/composer/packagist/issues/496), so for now we're going to stick with this namespace-different-from-vendor thing :/
3. Laravel is a great framework but the maintainer is some sort of [benevolent dictator](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life)... Taylor Otwell takes a lot of weird decisions that sometimes confuses us. Some of them are simplifying validation so much it's almost useless. The validation works in a _stitch-it-were-you-want_ model. That's why Ardent was created, and that's why I recently forked Laravalid to provide validation on model Forms as well through Ardent. I'm still working out a way to integrate `FormRequest` with Ardent (#254). I've had some trouble with [the routing](https://github.com/laravel/framework/issues/10659) and some other bugs for instance, where they say "won't fix it, too much trouble"
