### ISSUE TITLE
Is the current source compatible with Laravel 5+ ?  

### ISSUE THREAD

**Issue by curtd59** [laravel-ardent/ardent#309]
This is an extremely valuable package but it looks abandoned?  And I can't tell what versions it's compatible with.
Help?  -thanks.

**Comment by spyp** [comment]
its ok with 5.5 so far i used and its compatible

**Comment by Namoshek** [comment]
There has been a breaking change to laravels [Eloquent\Model::morphTo()](https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L179) method in [v5.6](https://github.com/laravel/framework/blame/master/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L179) which makes it incompatible with the [Ardent::morpthTo()](../blob/master/src/Ardent/Ardent.php#L451) method. So in case this repository is not maintained anymore (which seems to be the case, the last update was two years ago), I would stay away from it in case you want to use Laravel 5.6.

Nevertheless, it is quite straight forward to build your own Ardent-like base model. Many of the 1000 lines of code in the Ardent model class are not necessary (e.g. the simplified relationship notation) and incompatible with the current Eloquent model anyway. My own implementation (as I had to get rid of Ardent because of aforementioned reason) has about 350 LOC (phpDoc). As it is very untested, I'm not willing to share it though - sorry.

**Comment by spyp** [comment]
Hi yep i fix ardent for 5.6 but you are right i should build my own ardent
tnx for updating me

**Comment by igorsantos07** [comment]
Well, I'll stop being selfish here.
I've been very protective of this guy as I would hate to see breaking PRs
entering the project and making the experience even worse for other
developers...

I sort of slowed down development as I saw a huge need for tests before
proceeding with some important refactors, but as OS is free and power
isn't, I never had means to dedicate time to it as I had when it was in use
of a project of mine.


But I'm past or thinking I'll get back to it. I already adopted it from a
previous maintainer shortly after his "disappearance", and I guess I should
move along as well.


If anyone would like to step up and take more care of this as I've done so
far, ping me and I'll make arrangements.

**Comment by spyp** [comment]
ping @igorsantos07 
if u need help i'm ready to rebuild this amazing package :)
Hope i can help on this

**Comment by igorsantos07** [comment]
I've added @spyp as contributor, if this is not too late.

Some things have happened around here and I found some space to do static reviews and overview the repository, at least :)

I've merged a couple of compatibility PRs and will be releasing as a new minor later.
